name: Hello World Slack

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  post-to-slack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node jobs/hello-world.mjs
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
